name: 'Java-Gradle default setup'
description: 'Setup Java and Gradle environment for building, with opinionated default settings'

inputs:
  java_version:
    description: 'Java version to use'
    required: true
  java_distribution:
    description: 'Java distribution to use'
    required: false
    default: 'temurin'
  java_package:
    description: 'The package type (jdk, jre, jdk+fx, jre+fx)'
    required: false
    default: 'jdk'
  gradle_wrapper_validation:
    description: 'Validate Gradle wrapper'
    required: false
    default: 'true'
  gradle_wrapper_allow_snapshots:
    description: 'Allow Gradle wrapper snapshots'
    required: false
    default: 'false'
  gradle_dependency_graph:
    description: |
      Specifies if a GitHub dependency snapshot should be generated for each Gradle build, and if so, how.
      Valid values are 'disabled', 'generate', 'generate-and-submit', 'generate-submit-and-upload', 'generate-and-upload', and 'download-and-submit'.
    required: false
    default: 'generate-submit-and-upload'

outputs:
  java_version:
    description: Version of Java that was setup by the action
    value: ${{ steps.setup-java.outputs.version }}
  java_distribution:
    description: Distribution of Java that was setup by the action
    value: ${{ steps.setup-java.outputs.distribution }}
  java_path:
    description: Path to Java that was setup by the action
    value: ${{ steps.setup-java.outputs.java }}
  gradle_version:
    description: Version of Gradle that was setup by the action
    value: ${{ steps.setup-gradle.outputs.gradle-version }}

runs:
  using: 'composite'
  steps:
    - name: Set up Java
      id: setup-java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distribution }}
        java-package: ${{ inputs.java_package }}

    - name: Setup Gradle
      id: setup-gradle
      uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5
      with:
        validate-wrappers: ${{ inputs.gradle_wrapper_validation }}
        allow-snapshot-wrappers: ${{ inputs.gradle_wrapper_allow_snapshots }}
        dependency-graph: ${{ inputs.gradle_dependency_graph }}

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
      shell: bash
