name: 'Rust Clippy'
description: 'Reusable workflow that runs clippy to catch common mistakes and improve your Rust code.'

on:
  workflow_call:
    inputs:
      source_directory:
        description: 'Directory containing the Rust project'
        required: false
        type: string
        default: '.'
      clippy_arguments:
        description: 'Arguments to pass to clippy'
        required: false
        type: string
        default: '--all-features --all-targets'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-rust-clippy
  cancel-in-progress: true

permissions: {}

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to checkout the code
      checks: write # Required to annotate the commit with clippy warnings
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
          persist-credentials: false

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          components: clippy

      - name: Run clippy
        uses: clechasseur/rs-clippy-check@286fd9545eb133adad54b4af34bcb642e266ddd1 # v5
        with:
          args: ${{ inputs.clippy_arguments }}
