name: 'Setup App Git Identity'
description: 'Configures git with the identity of a GitHub App bot and outputs the bot details.'

inputs:
  app-slug:
    description: 'The slug of the GitHub App (e.g. "my-app").'
    required: true
  token:
    description: 'The GitHub token to use for API requests.'
    required: true

outputs:
  bot-name:
    description: 'The username of the bot (e.g. app-slug[bot])'
    value: ${{ steps.get-bot-info.outputs.bot-name }}
  bot-email:
    description: 'The email of the bot'
    value: ${{ steps.get-bot-info.outputs.bot-email }}
  bot-id:
    description: 'The ID of the bot user'
    value: ${{ steps.get-bot-info.outputs.bot-id }}

runs:
  using: 'composite'
  steps:
    - name: Get Bot User Info
      id: get-bot-info
      uses: TimSchoenle/actions/actions/common/get-app-git-identity@26754381479003bd81b51fffecc97f1faa20a9bf # actions-common-get-app-git-identity-v1.1.0
      with:
        app-slug: ${{ inputs.app-slug }}
        token: ${{ inputs.token }}

    - name: Configure Git Identity
      id: configure-git
      shell: bash
      env:
        BOT_NAME: ${{ steps.get-bot-info.outputs.bot-name }}
        BOT_EMAIL: ${{ steps.get-bot-info.outputs.bot-email }}
      run: |
        echo "Configuring git user as $BOT_NAME <$BOT_EMAIL>..."
        git config user.name "$BOT_NAME"
        git config user.email "$BOT_EMAIL"
