name: 'Maintenance Auto-approve-renovate'
description: 'Reusable workflow to auto approve Renovate PRs, this is useful to auto merge Renovate PRs which have auto-merge enabled.'

on:
  workflow_call:
    inputs:
      renovate-user-id:
        description: 'User ID of the renovate bot'
        required: false
        type: string
        default: '29139614'
    secrets:
      token:
        description: 'GitHub Token with permission to approve pull requests'
        required: true

jobs:
  auto-approve:
    name: Auto-approve PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check PR Author
        id: check_author
        env:
          PR_AUTHOR_ID: ${{ github.event.pull_request.user.id }}
          RENOVATE_USER_ID: ${{ inputs.renovate-user-id }}
        run: |
          echo "PR Author ID: $PR_AUTHOR_ID"
          echo "Expected Renovate User ID: $RENOVATE_USER_ID"

          if [[ "$PR_AUTHOR_ID" != "$RENOVATE_USER_ID" ]]; then
            echo "PR author ID is '$PR_AUTHOR_ID', not '$RENOVATE_USER_ID'. Skipping."
            echo "match=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "match=true" >> $GITHUB_OUTPUT

      - name: Verify Commits and Signatures
        id: verify_commits
        if: steps.check_author.outputs.match == 'true'
        uses: TimSchoenle/actions/actions/helper/verify-commit-authors@2e1d6fbc0347a1c1cdc666b2b208a9125686bca6 # actions-helper-verify-commit-authors-v1.1.0
        with:
          pr_url: ${{ github.event.pull_request.html_url }}
          github_token: ${{ secrets.token }}
          user_ids: ${{ inputs.renovate-user-id }}

      - name: Auto-approve
        if: steps.verify_commits.outputs.verified == 'true'
        env:
          GH_TOKEN: ${{ secrets.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          echo "All checks passed. Approving PR..."
          gh pr review "$PR_URL" --approve --body "Auto-approved by workflow."
