name: 'Maintenance Auto-approve-renovate'
description: 'Reusable workflow to auto approve Renovate PRs, this is useful to auto merge Renovate PRs which have auto-merge enabled.'

on:
  workflow_call:
    inputs:
      renovate-user-id:
        description: 'User ID of the renovate bot'
        required: false
        type: string
        default: '29139614'
    secrets:
      token:
        description: 'GitHub Token with permission to approve pull requests'
        required: true

jobs:
  auto-approve:
    name: Auto-approve PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check PR Author
        id: check_author
        env:
          PR_AUTHOR_ID: ${{ github.event.pull_request.user.id }}
          RENOVATE_USER_ID: ${{ inputs.renovate-user-id }}
        run: |
          echo "PR Author ID: $PR_AUTHOR_ID"
          echo "Expected Renovate User ID: $RENOVATE_USER_ID"

          if [[ "$PR_AUTHOR_ID" != "$RENOVATE_USER_ID" ]]; then
            echo "PR author ID is '$PR_AUTHOR_ID', not '$RENOVATE_USER_ID'. Skipping."
            echo "match=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "match=true" >> $GITHUB_OUTPUT

      - name: Verify Commits and Signatures
        id: verify_commits
        if: steps.check_author.outputs.match == 'true'
        env:
          GH_TOKEN: ${{ secrets.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          RENOVATE_USER_ID: ${{ inputs.renovate-user-id }}
        run: |
          echo "Verifying commits and signatures for PR: $PR_URL"

          # Query GraphQL for commit authors (databaseId) and signature status
          QUERY='
            query($url: URI!) {
              resource(url: $url) {
                ... on PullRequest {
                  commits(last: 100) {
                    totalCount
                    nodes {
                      commit {
                        oid
                        authors(first: 20) {
                          nodes {
                            user {
                              databaseId
                            }
                          }
                        }
                        signature {
                          isValid
                          state
                        }
                      }
                    }
                  }
                }
              }
            }
          '

          INVALID_COMMITS=$(gh api graphql -F url="$PR_URL" -f query="$QUERY" | jq -r \
            --argjson USER_ID "$RENOVATE_USER_ID" \
            '
             if .data.resource.commits.totalCount > 100 then
               "FAILURE_TOO_MANY_COMMITS"
             else
               .data.resource.commits.nodes[] | select(
                 (.commit.authors.nodes | length == 0) or 
                 (.commit.authors.nodes[] | .user == null or .user.databaseId != $USER_ID) or 
                 (.commit.signature == null or .commit.signature.isValid != true)
               ) | .commit.oid
             end
            ')
            
          if [[ "$INVALID_COMMITS" == "FAILURE_TOO_MANY_COMMITS" ]]; then
             echo "PR has more than 100 commits. Auto-approval is unsafe without pagination."
             echo "match=false" >> $GITHUB_OUTPUT
             exit 0
          fi

          if [[ -n "$INVALID_COMMITS" ]]; then
             echo "Found invalid commits (author check or signature check failed):"
             echo "$INVALID_COMMITS"
             echo "Skipping approval."
             echo "match=false" >> $GITHUB_OUTPUT
             exit 0
          fi
          echo "match=true" >> $GITHUB_OUTPUT

      - name: Auto-approve
        if: steps.verify_commits.outputs.match == 'true'
        env:
          GH_TOKEN: ${{ secrets.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          echo "All checks passed. Approving PR..."
          gh pr review "$PR_URL" --approve --body "Auto-approved by workflow."
