name: 'Maintenance Auto-approve-renovate'
description: 'Reusable workflow to auto approve Renovate PRs, this is useful to auto merge Renovate PRs which have auto-merge enabled.'

on:
  workflow_call:
    inputs:
      user_ids:
        description: 'Comma-separated list of Database IDs of accepted authors (e.g. "29139614, 123456").'
        required: false
        type: string
        default: '29139614'
    secrets:
      token:
        description: 'GitHub Token with permission to approve pull requests'
        required: true

jobs:
  auto-approve:
    name: Auto-approve PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Check PR Author
        id: check_author
        env:
          PR_AUTHOR_ID: ${{ github.event.pull_request.user.id }}
          ALLOWED_USER_IDS: ${{ inputs.user_ids }}
        run: |
          echo "PR Author ID: $PR_AUTHOR_ID"
          echo "Allowed User IDs: $ALLOWED_USER_IDS"

          match=false
          # Replace commas with spaces to handle mixed delimiters
          # Then iterate over the space-separated list
          for id in ${ALLOWED_USER_IDS//,/ }; do
            if [[ "$id" == "$PR_AUTHOR_ID" ]]; then
              match=true
              break
            fi
          done

          if [[ "$match" != "true" ]]; then
            echo "PR author ID '$PR_AUTHOR_ID' is not in the allowed list. Skipping."
            echo "match=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "match=true" >> $GITHUB_OUTPUT

      - name: Verify Commits and Signatures
        id: verify_commits
        if: steps.check_author.outputs.match == 'true'
        uses: TimSchoenle/actions/actions/helper/verify-commit-authors@e8cf863e3d920951c02673d8a8a642a4aa7f789c # actions-helper-verify-commit-authors-v1.1.1
        with:
          pr_url: ${{ github.event.pull_request.html_url }}
          github_token: ${{ secrets.token }}
          user_ids: ${{ inputs.user_ids }}

      - name: Auto-approve
        if: steps.verify_commits.outputs.verified == 'true'
        env:
          GH_TOKEN: ${{ secrets.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          echo "All checks passed. Approving PR..."
          gh pr review "$PR_URL" --approve --body "Auto-approved by workflow."
