name: 'Maintenance Auto-approve-renovate'
description: 'Reusable workflow to auto approve Renovate PRs, this is useful to auto merge Renovate PRs which have auto-merge enabled.'

on:
  workflow_call:
    inputs:
      user_ids:
        description: 'Comma-separated list of Database IDs of accepted authors (e.g. "29139614, 123456").'
        required: false
        type: string
        default: '29139614'
      ignore_empty_prs:
        description: 'Ignore PRs with 0 changes. Renovate seems to sometimes create multiple lock-files PR without changing anything.'
        required: false
        type: boolean
        default: true
    secrets:
      token:
        description: 'GitHub Token with permission to approve pull requests'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-auto-approve-renovate
  cancel-in-progress: true

permissions: {}

jobs:
  auto-approve:
    name: Auto-approve PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # to approve PRs
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Auto-approve Renovate PRs
        uses: TimSchoenle/actions/actions/maintenance/auto-approve-pr@952c0858f31fc87a57429af70db8cda2d37c1642 # actions-maintenance-auto-approve-pr-v1.1.4
        with:
          token: ${{ secrets.token }}
          user_ids: ${{ inputs.user_ids }}
          branch_pattern: '^renovate\/.*$'
          reject_forks: 'true'
          ignore_empty_prs: ${{ inputs.ignore_empty_prs }}
