name: 'Get App Git Identity'
description: 'Resolves the git identity (username, email, user ID) for a GitHub App bot.'

inputs:
  app-slug:
    description: 'The slug of the GitHub App (e.g. "my-app").'
    required: true
  token:
    description: 'The GitHub token to use for API requests.'
    required: true

outputs:
  bot-name:
    description: 'The username of the bot (e.g. app-slug[bot])'
    value: ${{ steps.get-bot-info.outputs.bot-name }}
  bot-email:
    description: 'The email of the bot'
    value: ${{ steps.get-bot-info.outputs.bot-email }}
  bot-id:
    description: 'The ID of the bot user'
    value: ${{ steps.get-bot-info.outputs.bot-id }}

runs:
  using: 'composite'
  steps:
    - name: Get Bot User Info
      id: get-bot-info
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        APP_SLUG: ${{ inputs.app-slug }}
      run: |
        BOT_USERNAME="${APP_SLUG}[bot]"
        echo "Resolving ID for $BOT_USERNAME..."

        BOT_ID=$(gh api "/users/${BOT_USERNAME}" --jq .id)

        if [ -z "$BOT_ID" ]; then
          echo "::error::Could not find user ID for ${BOT_USERNAME}"
          exit 1
        fi

        BOT_EMAIL="${BOT_ID}+${BOT_USERNAME}@users.noreply.github.com"

        echo "bot-id=$BOT_ID" >> $GITHUB_OUTPUT
        echo "bot-name=$BOT_USERNAME" >> $GITHUB_OUTPUT
        echo "bot-email=$BOT_EMAIL" >> $GITHUB_OUTPUT
