import { describe, expect, it } from 'vitest';

import { alignLines, describeFirstDifference, diffContent, renderDiff, toLines } from './diff.js';

describe('toLines', () => {
  it('treats a trailing newline as a terminator, not as an empty last line', () => {
    expect(toLines('a\nb\n')).toEqual(['a', 'b']);
    expect(toLines('a\nb')).toEqual(['a', 'b']);
  });

  it('keeps a genuinely blank line in the middle', () => {
    expect(toLines('a\n\nb\n')).toEqual(['a', '', 'b']);
  });

  // A checkout's line endings are a property of the runner's git configuration, not of the contract.
  // A check that failed on Windows and passed on Linux would be reporting the wrong thing entirely.
  it('folds CRLF, so the same content compares equal on either platform', () => {
    expect(toLines('a\r\nb\r\n')).toEqual(['a', 'b']);
    expect(diffContent('a\nb\n', 'a\r\nb\r\n')).toBeUndefined();
  });

  it('reads an empty document as no lines at all', () => {
    expect(toLines('')).toEqual([]);
  });
});

describe('diffContent', () => {
  it('reports nothing for identical content', () => {
    expect(diffContent('LABEL a=1\nLABEL b=2\n', 'LABEL a=1\nLABEL b=2\n')).toBeUndefined();
  });

  it('marks a removed line and an added one', () => {
    const difference = diffContent('a\nb\nc\n', 'a\nB\nc\n');

    expect(difference).toContain('- b');
    expect(difference).toContain('+ B');
    expect(difference).toContain('  a');
  });

  // The case a line-count check passes: the block is a strict superset, so comparing two of three
  // lines finds no difference at all.
  it('catches a label that was dropped from an otherwise identical block', () => {
    const generated = 'LABEL a=1\nLABEL b=2\nLABEL c=3\n';
    const committed = 'LABEL a=1\nLABEL b=2\n';

    expect(diffContent(generated, committed)).toContain('- LABEL c=3');
  });

  it('catches a fourth label the generated block does not publish', () => {
    expect(diffContent('LABEL a=1\n', 'LABEL a=1\nLABEL rogue=1\n')).toContain('+ LABEL rogue=1');
  });

  it('catches a renamed prefix even when the shape is unchanged', () => {
    const difference = diffContent('LABEL dev.terrace.x=1\n', 'LABEL dev.other.x=1\n');

    expect(difference).toContain('- LABEL dev.terrace.x=1');
    expect(difference).toContain('+ LABEL dev.other.x=1');
  });

  // Pedantic on purpose. A file holding a single newline holds one empty line; an empty file holds
  // none. Every comparison here is between generated bytes and committed bytes, and a check that
  // shrugged at a stray newline would be the wrong kind of tolerant.
  it('separates an empty file from one holding a single newline', () => {
    expect(toLines('')).toEqual([]);
    expect(toLines('\n')).toEqual(['']);
    expect(diffContent('', '\n')).toBe('+ ');
  });
});

describe('renderDiff', () => {
  it('elides a long run of unchanged lines rather than flooding the log', () => {
    const long = Array.from({ length: 200 }, (_, index) => `line ${index}`);
    const changed = [...long];
    changed[100] = 'changed';

    const rendered = renderDiff(alignLines(long, changed) ?? []);

    expect(rendered).toContain('unchanged lines');
    expect(rendered).toContain('- line 100');
    expect(rendered).toContain('+ changed');
    // Three lines of context each side, the change itself, and the two elision notes.
    expect(rendered.split('\n')).toHaveLength(10);
  });

  // The whole difference becomes one annotation, and GitHub truncates a long one without saying so.
  // A report that says how much it left out beats one that is silently cut.
  it('bounds a wholly rewritten document to a readable report and says what it dropped', () => {
    const before = Array.from({ length: 500 }, (_, index) => `old ${index}`);
    const after = Array.from({ length: 500 }, (_, index) => `new ${index}`);

    const rendered = renderDiff(alignLines(before, after) ?? []);
    const lines = rendered.split('\n');

    expect(lines).toHaveLength(61);
    expect(lines.at(-1)).toMatch(/… 940 further lines not shown …/);
  });

  it('truncates a single enormous line', () => {
    const rendered = renderDiff(alignLines(['x'.repeat(1000)], ['y'.repeat(1000)]) ?? []);

    expect(rendered).toContain('…');
    expect(rendered.length).toBeLessThan(600);
  });
});

describe('alignLines', () => {
  it('matches identical head and tail off before aligning, so the table stays small', () => {
    const head = Array.from({ length: 5000 }, (_, index) => `h${index}`);
    const tail = Array.from({ length: 5000 }, (_, index) => `t${index}`);

    // Ten thousand identical lines either side of a one-line change would be 10^8 cells if the
    // whole document were aligned. Trimming first is what keeps it a handful.
    const ops = alignLines([...head, 'before', ...tail], [...head, 'after', ...tail]);

    expect(ops?.filter((op) => op.kind !== 'equal')).toEqual([
      { kind: 'remove', line: 'before' },
      { kind: 'add', line: 'after' },
    ]);
  });

  it('gives up on a differing region too large to align', () => {
    const left = Array.from({ length: 2000 }, (_, index) => `a${index}`);
    const right = Array.from({ length: 2000 }, (_, index) => `b${index}`);

    expect(alignLines(left, right)).toBeUndefined();
  });

  it('reports two identical sequences as all equal', () => {
    expect(alignLines(['a', 'b'], ['a', 'b'])?.every((op) => op.kind === 'equal')).toBe(true);
  });
});

describe('describeFirstDifference', () => {
  it('names the one-indexed line the two part ways on', () => {
    expect(describeFirstDifference(['a', 'b'], ['a', 'B'])).toContain('line 2');
  });

  it('says which side ran out when one is a prefix of the other', () => {
    expect(describeFirstDifference(['a'], ['a', 'b'])).toContain('<end of generated output>');
    expect(describeFirstDifference(['a', 'b'], ['a'])).toContain('<end of file>');
  });

  it('is what a comparison too large to align falls back to', () => {
    const left = Array.from({ length: 2000 }, (_, index) => `a${index}`).join('\n');
    const right = Array.from({ length: 2000 }, (_, index) => `b${index}`).join('\n');

    expect(diffContent(left, right)).toContain('Too large to align line by line');
  });
});
