name: 'Rust Auto-format'
description: 'Reusable workflow that runs cargo fmt and commits changes.'

on:
  workflow_call:
    inputs:
      source_directory:
        description: 'Directory containing the Rust project'
        required: false
        type: string
        default: '.'
      commit_message:
        description: 'Commit message for auto-formatted changes'
        required: false
        type: string
        default: 'style: auto-format rust code'
    secrets:
      APP_ID:
        required: true
        description: 'GitHub App ID for bot authentication'
      PRIVATE_KEY:
        required: true
        description: 'GitHub App Private Key'
    outputs:
      changes_detected:
        description: 'True if changes were committed'
        value: ${{ jobs.fmt.outputs.changes_detected }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-rust-auto-format
  cancel-in-progress: true

permissions: {}

jobs:
  fmt:
    name: Auto Format
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      changes_detected: ${{ steps.auto-commit.outputs.changes_detected }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Generate Bot Token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          token: ${{ steps.generate_token.outputs.token }}

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          components: rustfmt

      - name: Run cargo fmt
        working-directory: ${{ inputs.source_directory }}
        run: cargo fmt

      - name: Commit and Push if changed
        id: auto-commit
        uses: TimSchoenle/actions/actions/common/commit-changes@8f15b94f827ea2005c0e32cadc86bb50969633dd # actions-common-commit-changes-v1.1.4
        with:
          commit_message: ${{ inputs.commit_message }}
          token: ${{ steps.generate_token.outputs.token }}
