name: 'Common Modify YAML'
description: 'A action to modify a value in a YAML file while strictly preserving comments and structure'
inputs:
  file:
    description: 'Path to the YAML file'
    required: true
  key:
    description: 'Dot-notation key path'
    required: true
  value:
    description: 'Value to set'
    required: true
outputs:
  old-value:
    description: 'Value before modification'
    value: ${{ steps.set-outputs.outputs.old-value }}
  new-value:
    description: 'Value after modification'
    value: ${{ steps.set-outputs.outputs.new-value }}
runs:
  using: 'composite'
  steps:
    - name: Validate File Exists
      shell: bash
      run: |
        if [ ! -f "${{ inputs.file }}" ]; then
          echo "::error::File not found: ${{ inputs.file }}"
          exit 1
        fi
    
    - name: Get Old Value
      id: old
      shell: bash
      run: |
        OLD_VALUE=$(yq eval ".${{ inputs.key }}" "${{ inputs.file }}")
        if [ "$OLD_VALUE" == "null" ]; then
          echo "::error::Key '${{ inputs.key }}' not found in ${{ inputs.file }}"
          exit 1
        fi
        echo "value=$OLD_VALUE" >> "$GITHUB_OUTPUT"
        echo "Old value: $OLD_VALUE"
    
    - name: Modify YAML
      shell: bash
      run: |
        # Detect value type and set appropriately
        VALUE="${{ inputs.value }}"
        
        # Check if it's a boolean
        if [ "$VALUE" == "true" ] || [ "$VALUE" == "false" ]; then
          yq eval -i ".${{ inputs.key }} = $VALUE" "${{ inputs.file }}"
        # Check if it's a number
        elif [[ "$VALUE" =~ ^-?[0-9]+\.?[0-9]*$ ]]; then
          yq eval -i ".${{ inputs.key }} = $VALUE" "${{ inputs.file }}"
        # Otherwise treat as string (with quotes)
        else
          yq eval -i ".${{ inputs.key }} = \"$VALUE\"" "${{ inputs.file }}"
        fi
        
        echo "✅ Modified ${{ inputs.key }}"
        echo "  From: ${{ steps.old.outputs.value }}"
        echo "  To:   $VALUE"
    
    - name: Set Outputs
      id: set-outputs
      shell: bash
      run: |
        echo "old-value=${{ steps.old.outputs.value }}" >> "$GITHUB_OUTPUT"
        echo "new-value=${{ inputs.value }}" >> "$GITHUB_OUTPUT"
