name: 'Common Modify YAML'
description: 'A action to modify a value in a YAML file while strictly preserving comments and structure'
inputs:
  file:
    description: 'Path to the YAML file'
    required: true
  key:
    description: 'Dot-notation key path'
    required: true
  value:
    description: 'Value to set'
    required: true
outputs:
  old-value:
    description: 'Value before modification'
    value: ${{ steps.set-outputs.outputs.old-value }}
  new-value:
    description: 'Value after modification'
    value: ${{ steps.set-outputs.outputs.new-value }}
runs:
  using: 'composite'
  steps:
    - name: Validate and Get Old Value
      id: old
      shell: bash
      run: |
        FILE="${{ inputs.file }}"
        KEY="${{ inputs.key }}"
        
        if [ ! -f "$FILE" ]; then
          echo "::error::File not found: $FILE"
          exit 1
        fi
        
        # Use yq to validate structure and get old value
        OLD_VALUE=$(yq eval ".$KEY" "$FILE")
        if [ "$OLD_VALUE" == "null" ]; then
          echo "::error::Key '$KEY' not found in $FILE"
          exit 1
        fi
        
        echo "value=$OLD_VALUE" >> "$GITHUB_OUTPUT"
        echo "Old value: $OLD_VALUE"
    
    - name: Modify YAML
      shell: bash
      run: |
        FILE="${{ inputs.file }}"
        KEY="${{ inputs.key }}"
        VALUE="${{ inputs.value }}"
        
        # Extract the final key name from dot notation
        FINAL_KEY="${KEY##*.}"
        
        # Detect value type and format appropriately
        if [ "$VALUE" == "true" ] || [ "$VALUE" == "false" ]; then
          FORMATTED_VALUE="$VALUE"
        elif [[ "$VALUE" =~ ^-?[0-9]+\.?[0-9]*$ ]]; then
          FORMATTED_VALUE="$VALUE"
        else
          # String - check if it needs quotes (contains special YAML characters)
          # Simple approach: quote if it contains spaces, colons, or common special chars
          case "$VALUE" in
            *[\ :{}[\],\&*#?|\-\<\>=!%@\`]*)
              FORMATTED_VALUE="\"${VALUE//\"/\\\"}\""
              ;;
            *)
              FORMATTED_VALUE="$VALUE"
              ;;
          esac
        fi
        
        # Use perl for in-place editing with perfect preservation
        perl -i -pe "
          if (/^(\s*)${FINAL_KEY}\s*:\s*(.*)$/) {
            my \$indent = \$1;
            my \$rest = \$2;
            my \$comment = '';
            if (\$rest =~ /(#.*)$/) {
              \$comment = '  ' . \$1;
            }
            \$_ = \$indent . '${FINAL_KEY}: ${FORMATTED_VALUE}' . \$comment . \"\\n\";
          }
        " "$FILE"
        
        echo "✅ Modified $KEY to: $VALUE"
    
    - name: Set Outputs
      id: set-outputs
      shell: bash
      run: |
        echo "old-value=${{ steps.old.outputs.value }}" >> "$GITHUB_OUTPUT"
        echo "new-value=${{ inputs.value }}" >> "$GITHUB_OUTPUT"
