name: 'Common Modify YAML'
description: 'A action to modify a value in a YAML file while strictly preserving comments and structure'
inputs:
  file:
    description: 'Path to the YAML file'
    required: true
  key:
    description: 'Dot-notation key path'
    required: true
  value:
    description: 'Value to set'
    required: true
outputs:
  old-value:
    description: 'Value before modification'
    value: ${{ steps.set-outputs.outputs.old-value }}
  new-value:
    description: 'Value after modification'
    value: ${{ steps.set-outputs.outputs.new-value }}
runs:
  using: 'composite'
  steps:
    - name: Validate and Get Old Value
      id: old
      shell: bash
      run: |
        FILE="${{ inputs.file }}"
        KEY="${{ inputs.key }}"
        
        if [ ! -f "$FILE" ]; then
          echo "::error::File not found: $FILE"
          exit 1
        fi
        
        # Use yq to validate structure and get old value
        OLD_VALUE=$(yq eval ".$KEY" "$FILE")
        if [ "$OLD_VALUE" == "null" ]; then
          echo "::error::Key '$KEY' not found in $FILE"
          exit 1
        fi
        
        echo "value=$OLD_VALUE" >> "$GITHUB_OUTPUT"
        echo "Old value: $OLD_VALUE"

    - name: Modify YAML
      shell: bash
      run: |
        FILE="${{ inputs.file }}"
        KEY="${{ inputs.key }}"
        VALUE="${{ inputs.value }}"
        
        # Use yq to find the EXACT line number for this key path
        # yq eval --unwrapScalar gives us line:col info with -oj (output as JSON)
        LINE_INFO=$(yq eval ".$KEY | line" "$FILE")
        
        if [ -z "$LINE_INFO" ] || [ "$LINE_INFO" == "null" ]; then
          echo "::error::Could not find line number for key: $KEY"
          exit 1
        fi
        
        # Extract final key name
        FINAL_KEY="${KEY##*.}"
        
        # Detect value type and format appropriately
        if [ "$VALUE" == "true" ] || [ "$VALUE" == "false" ]; then
          FORMATTED_VALUE="$VALUE"
        elif [[ "$VALUE" =~ ^-?[0-9]+\.?[0-9]*$ ]]; then
          FORMATTED_VALUE="$VALUE"
        else
          # String - minimal quoting
          case "$VALUE" in
            *[\ :{}[\],\&*#?|\<\>=!%@\`]*)
              FORMATTED_VALUE="\"${VALUE//\"/\\\"}\""
              ;;
            *)
              FORMATTED_VALUE="$VALUE"
              ;;
          esac
        fi
        
        # Use sed to modify ONLY the specific line number
        # Pattern explanation:
        # - Capture group 1: leading whitespace (indent)
        # - Match: key name, colon, spaces, old value
        # - Capture group 2: optional comment (everything from # to end)
        # - Replace with: indent + key + new value + comment (if present)
        
        # Read the line to extract comment
        ORIGINAL_LINE=$(sed -n "${LINE_INFO}p" "$FILE")
        COMMENT=""
        if [[ "$ORIGINAL_LINE" =~ (#.*) ]]; then
          COMMENT="  ${BASH_REMATCH[1]}"
        fi
        
        # Use sed to replace the line while preserving indent
        sed -i "${LINE_INFO}s|^\([[:space:]]*\)${FINAL_KEY}[[:space:]]*:.*$|\1${FINAL_KEY}: ${FORMATTED_VALUE}${COMMENT}|" "$FILE"
        
        echo "✅ Modified $KEY (line $LINE_INFO) to: $VALUE"

    - name: Set Outputs
      id: set-outputs
      shell: bash
      run: |
        echo "old-value=${{ steps.old.outputs.value }}" >> "$GITHUB_OUTPUT"
        echo "new-value=${{ inputs.value }}" >> "$GITHUB_OUTPUT"
