name: 'Common Modify YAML'
description: 'A action to modify a value in a YAML file while strictly preserving comments and structure'
inputs:
  file:
    description: 'Path to the YAML file'
    required: true
  key:
    description: 'Dot-notation key path'
    required: true
  value:
    description: 'Value to set'
    required: true
outputs:
  old-value:
    description: 'Value before modification'
    value: ${{ steps.modify.outputs.old-value }}
  new-value:
    description: 'Value after modification'
    value: ${{ steps.modify.outputs.new-value }}
runs:
  using: 'composite'
  steps:
    - name: Modify YAML
      id: modify
      shell: bash
      env:
        INPUT_FILE: ${{ inputs.file }}
        INPUT_KEY: ${{ inputs.key }}
        INPUT_VALUE: ${{ inputs.value }}
        PYTHONPATH: ${{ github.action_path }}/src
        ACTION_PATH: ${{ github.action_path }}
      run: python3 "$ACTION_PATH/src/main.py"
