name: 'Common Modify YAML'
description: 'A action to modify a value in a YAML file while strictly preserving comments and structure'
inputs:
  file:
    description: 'Path to the YAML file'
    required: true
  key:
    description: 'Dot-notation key path'
    required: true
  value:
    description: 'Value to set'
    required: true
outputs:
  old-value:
    description: 'Value before modification'
    value: ${{ steps.set-outputs.outputs.old-value }}
  new-value:
    description: 'Value after modification'
    value: ${{ steps.set-outputs.outputs.new-value }}
runs:
  using: 'composite'
  steps:
    - name: Validate and Get Old Value
      id: old
      shell: bash
      run: |
        FILE="${{ inputs.file }}"
        KEY="${{ inputs.key }}"
        
        if [ ! -f "$FILE" ]; then
          echo "::error::File not found: $FILE"
          exit 1
        fi
        
        # Use yq to validate structure and get old value
        OLD_VALUE=$(yq eval ".$KEY" "$FILE")
        if [ "$OLD_VALUE" == "null" ]; then
          echo "::error::Key '$KEY' not found in $FILE"
          exit 1
        fi
        
        echo "value=$OLD_VALUE" >> "$GITHUB_OUTPUT"
        echo "Old value: $OLD_VALUE"
    
    - name: Modify YAML
      shell: python
      env:
        FILE: ${{ inputs.file }}
        KEY: ${{ inputs.key }}
        VALUE: ${{ inputs.value }}
      run: |
        import os
        import re
        
        file_path = os.environ['FILE']
        key_path = os.environ['KEY']
        value = os.environ['VALUE']
        
        # Extract final key from dot notation
        final_key = key_path.split('.')[-1]
        
        # Detect value type
        if value in ('true', 'false'):
            formatted_value = value
        elif re.match(r'^-?[0-9]+\.?[0-9]*$', value):
            formatted_value = value
        else:
            # String - quote if needed
            if any(c in value for c in ' :{}[],&*#?|-<>=!%@`'):
                formatted_value = f'"{value.replace(chr(34), chr(92)+chr(34))}"'
            else:
                formatted_value = value
        
        # Read ALL lines (preserves blank lines perfectly)
        with open(file_path, 'r') as f:
            lines = f.readlines()
        
        # Process each line
        pattern = re.compile(rf'^(\s*){re.escape(final_key)}\s*:\s*(.*)$')
        
        for i, line in enumerate(lines):
            match = pattern.match(line)
            if match:
                indent = match.group(1)
                rest = match.group(2)
                
                # Extract inline comment if present
                comment_match = re.search(r'(#.*)$', rest)
                comment = ('  ' + comment_match.group(1)) if comment_match else ''
                
                # Replace line
                lines[i] = f'{indent}{final_key}: {formatted_value}{comment}\n'
                break
        
        # Write ALL lines back (preserves everything)
        with open(file_path, 'w') as f:
            f.writelines(lines)
        
        print(f'✅ Modified {key_path} to: {value}')
    
    - name: Set Outputs
      id: set-outputs
      shell: bash
      run: |
        echo "old-value=${{ steps.old.outputs.value }}" >> "$GITHUB_OUTPUT"
        echo "new-value=${{ inputs.value }}" >> "$GITHUB_OUTPUT"
