name: 'Rust Coverage (Codecov)'
description: 'Action that runs cargo llvm-cov to generate code coverage and uploads to Codecov.'

inputs:
  codecov_token:
    description: 'Token for Codecov'
    required: true
  repository:
    description: 'Target repository in the format owner/repo. Defaults to the current repository.'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'Target branch to checkout. Defaults to the current branch.'
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  source_directory:
    description: 'Directory containing the Rust project'
    required: false
    default: '.'
  test_arguments:
    description: 'Additional arguments to pass to cargo nextest'
    required: false
    default: '--all-features --workspace'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: ${{ inputs.repository }}
        persist-credentials: false
        fetch-depth: 0
        ref: ${{ inputs.branch }}

    - name: Install stable toolchain
      uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4

    - name: Install cargo-llvm-cov and nextest
      uses: taiki-e/install-action@a164de717a0ee9284c2d9db1c6016a4c339cd333 # v2.69.14
      with:
        tool: cargo-llvm-cov,nextest

    - name: Generate code coverage
      shell: bash
      env:
        TEST_ARGUMENTS: ${{ inputs.test_arguments }}
      working-directory: ${{ inputs.source_directory }}
      run: |
        # shellcheck disable=SC2206
        args=($TEST_ARGUMENTS)
        cargo llvm-cov nextest --lcov --output-path lcov.info "${args[@]}"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
      with:
        token: ${{ secrets.codecov_token }}
        files: lcov.info
        fail_ci_if_error: true
