name: Verify {{capitalizedPackageName}} {{capitalizedSubAction}}

on:
  push:
    branches:
      - main
    paths:
      - 'actions/{{packageName}}/{{subAction}}/**'
      - '.github/workflows/verify-action-{{packageName}}-{{subAction}}.yaml'
  pull_request:
    paths:
      - 'actions/{{packageName}}/{{subAction}}/**'
      - '.github/workflows/verify-action-{{packageName}}-{{subAction}}.yaml'

permissions: {}

jobs:
  verify:
    name: Verify {{capitalizedSubAction}}
    runs-on: ubuntu-latest
    permissions:
      contents: read # to fetch code
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Test {{subAction}}
        uses: ./actions/{{packageName}}/{{subAction}}
