name: 'Delete-Branch'
description: 'Deletes a branch from a repository. Fails gracefully if the branch does not exist.'

inputs:
  token:
    description: 'GitHub token'
    required: true
  repository:
    description: 'Repository name (e.g. owner/repo)'
    required: true
    default: ${{ github.repository }}
  branch_name:
    description: 'The name of the branch to delete'
    required: true

outputs:
  deleted:
    description: "'true' if the branch was deleted, 'false' if it did not exist or could not be deleted"
    value: ${{ steps.delete-branch.outputs.deleted }}

runs:
  using: 'composite'
  steps:
    - name: Delete Branch
      id: delete-branch
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPO: ${{ inputs.repository }}
        BRANCH: ${{ inputs.branch_name }}
      run: |
        echo "Attempting to delete branch: $BRANCH in repo: $REPO"

        # Check if branch exists first to avoid error noise if it doesn't
        if gh api "/repos/$REPO/git/refs/heads/$BRANCH" > /dev/null 2>&1; then
          if gh api -X DELETE "/repos/$REPO/git/refs/heads/$BRANCH"; then
            echo "deleted=true" >> "$GITHUB_OUTPUT"
            echo "✅ Branch '$BRANCH' deleted successfully."
          else
            echo "deleted=false" >> "$GITHUB_OUTPUT"
            echo "::warning::Failed to delete branch '$BRANCH'."
          fi
        else
          echo "deleted=false" >> "$GITHUB_OUTPUT"
          echo "Branch '$BRANCH' does not exist. Skipping delete."
        fi
