name: 'Verify Commit Authors'
description: 'Verifies that all commits in a PR are authored by a specific set of users and are signed.'
inputs:
  pr_url:
    description: 'The URL of the Pull Request to verify.'
    required: true
  github_token:
    description: 'GitHub Token with permission to read PRs.'
    required: true
  user_ids:
    description: 'Comma-separated list of Database IDs of accepted authors (e.g. "29139614, 123456").'
    required: true
outputs:
  verified:
    description: 'True if all commits are verified, false otherwise.'
  invalid_commits:
    description: 'List of SHAs that failed verification.'
runs:
  using: 'node20'
  main: 'dist/index.js'
