name: 'Common Read YAML'
description: 'A action to read a value from a YAML file using dot notation'
inputs:
  file:
    description: 'Path to the YAML file'
    required: true
  key:
    description: 'Dot-notation key path (e.g. image.tag)'
    required: true
outputs:
  value:
    description: 'The value of the key'
    value: ${{ steps.read.outputs.value }}
runs:
  using: 'composite'
  steps:
    - name: Validate File Exists
      shell: bash
      env:
        INPUT_FILE: ${{ inputs.file }}
      run: |
        if [ ! -f "$INPUT_FILE" ]; then
          echo "::error::File not found: $INPUT_FILE"
          exit 1
        fi

    - name: Read YAML Value
      id: read
      shell: bash
      env:
        INPUT_KEY: ${{ inputs.key }}
        INPUT_FILE: ${{ inputs.file }}
      run: |
        VALUE=$(yq eval ".$INPUT_KEY" "$INPUT_FILE")

        if [ "$VALUE" == "null" ]; then
          echo "::error::Key '$INPUT_KEY' not found in $INPUT_FILE"
          exit 1
        fi

        echo "value=$VALUE" >> "$GITHUB_OUTPUT"
        echo "✅ Read value: $VALUE"
