name: 'Common Read YAML'
description: 'A action to read a value from a YAML file using dot notation'
inputs:
  file:
    description: 'Path to the YAML file'
    required: true
  key:
    description: 'Dot-notation key path (e.g. image.tag)'
    required: true
outputs:
  value:
    description: 'The value of the key'
    value: ${{ steps.read.outputs.value }}
runs:
  using: 'composite'
  steps:
    - name: Validate File Exists
      shell: bash
      run: |
        if [ ! -f "${{ inputs.file }}" ]; then
          echo "::error::File not found: ${{ inputs.file }}"
          exit 1
        fi
    
    - name: Read YAML Value
      id: read
      shell: bash
      run: |
        VALUE=$(yq eval ".${{ inputs.key }}" "${{ inputs.file }}")
        
        if [ "$VALUE" == "null" ]; then
          echo "::error::Key '${{ inputs.key }}' not found in ${{ inputs.file }}"
          exit 1
        fi
        
        echo "value=$VALUE" >> "$GITHUB_OUTPUT"
        echo "✅ Read value: $VALUE"
