name: 'Rust Clippy'
description: 'Action that runs clippy to catch common mistakes and improve your Rust code.'

inputs:
  repository:
    description: 'Target repository in the format owner/repo. Defaults to the current repository.'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'Target branch to checkout. Defaults to the current branch.'
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  source_directory:
    description: 'Directory containing the Rust project'
    required: false
    default: '.'
  clippy_arguments:
    description: 'Arguments to pass to clippy'
    required: false
    default: '--all-features --all-targets'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        repository: ${{ inputs.repository }}
        persist-credentials: false
        fetch-depth: 0
        ref: ${{ inputs.branch }}

    - name: Install stable toolchain
      uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      with:
        components: clippy

    - name: Run clippy
      uses: clechasseur/rs-clippy-check@62ad100473a5e6513e86407b859091115ec89ae3 # v6.0.5
      with:
        args: ${{ inputs.clippy_arguments }}
