name: 'Rust Clippy'
description: 'Action that runs clippy to catch common mistakes and improve your Rust code.'

inputs:
  repository:
    description: 'Target repository in the format owner/repo. Defaults to the current repository.'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'Target branch to checkout. Defaults to the current branch.'
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  source_directory:
    description: 'Directory containing the Rust project'
    required: false
    default: '.'
  clippy_arguments:
    description: 'Arguments to pass to clippy'
    required: false
    default: '--all-features --all-targets'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: ${{ inputs.repository }}
        persist-credentials: false
        fetch-depth: 0
        ref: ${{ inputs.branch }}

    - name: Install stable toolchain
      uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
      with:
        components: clippy

    - name: Run clippy
      uses: clechasseur/rs-clippy-check@3a0225255fc5c07aefde16d229e8479a137ddd8e # v6.0.3
      with:
        args: ${{ inputs.clippy_arguments }}
