name: 'Rust Clippy'
description: 'Action that runs clippy to catch common mistakes and improve your Rust code.'

inputs:
  repository:
    description: 'Target repository in the format owner/repo. Defaults to the current repository.'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'Target branch to checkout. Defaults to the current branch.'
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  source_directory:
    description: 'Directory containing the Rust project'
    required: false
    default: '.'
  clippy_arguments:
    description: 'Arguments to pass to clippy'
    required: false
    default: '--all-features --all-targets'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: ${{ inputs.repository }}
        persist-credentials: false
        fetch-depth: 0
        ref: ${{ inputs.branch }}

    - name: Install stable toolchain
      uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      with:
        components: clippy

    - name: Run clippy
      uses: clechasseur/rs-clippy-check@1e16925ceec49b64803a6abc5f6bbe79044c3bd4 # v6.0.4
      with:
        args: ${{ inputs.clippy_arguments }}
