name: 'Rust Cargo Check'
description: 'Reusable workflow that runs cargo check to verify Rust code compiles without errors.'

on:
  workflow_call:
    inputs:
      source_directory:
        description: 'Directory containing the Rust project'
        required: false
        type: string
        default: '.'
      check_arguments:
        description: 'Additional arguments to pass to cargo check'
        required: false
        type: string
        default: '--all-targets --all-features'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-rust-cargo-check
  cancel-in-progress: true

permissions: {}

jobs:
  cargo-check:
    name: Cargo Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2

      - name: Run cargo check
        env:
          CHECK_ARGUMENTS: ${{ inputs.check_arguments }}
        working-directory: ${{ inputs.source_directory }}
        run: |
          # shellcheck disable=SC2206
          args=($CHECK_ARGUMENTS)
          cargo check "${args[@]}"
