name: Common Test Workflow21345

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          NAME: ${{ inputs.name }}
        run: echo "Hello $NAME"
