name: Common Test Workflow21345

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - env:
          NAME: ${{ inputs.name }}
        run: echo "Hello $NAME"
