name: 'Commit Changes'
description: 'Commits changes using the GitHub API to ensure verified bot commits.'

inputs:
  commit_message:
    description: 'The commit message'
    required: true
  token:
    description: 'The GitHub token to use (must be an App installation token for verified commits)'
    required: true
  repository:
    description: 'Repository name to commit to (e.g. owner/repo)'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'Branch to commit to'
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  empty:
    description: Allow making an empty commit if there are no changes.
    required: false
    default: 'false'
  file_pattern:
    description: 'File pattern to commit'
    required: false
    default: '.'

outputs:
  commit_hash:
    description: 'The SHA of the created commit'
    value: ${{ steps.commit.outputs.commit-hash }}
  commit_url:
    description: 'The URL of the created commit.'
    value: ${{ steps.commit.outputs.commit-url }}
  changes_detected:
    description: 'True if changes were committed'
    value: ${{ steps.compatibility.outputs.changes_detected }}

runs:
  using: 'composite'
  steps:
    - name: Detect Changes
      id: detect
      shell: bash
      env:
        FILE_PATTERN: ${{ inputs.file_pattern }}
        ALLOW_EMPTY: ${{ inputs.empty }}
      run: |
        set -euo pipefail
        git config core.fileMode false

        FILES=()

        if [ -z "${FILE_PATTERN:-}" ] || [ "$FILE_PATTERN" = "." ]; then
          echo "::debug::No file pattern filter specified — checking all files"
          mapfile -t STATUS_LINES < <(git status --porcelain)
          RESOLVED_PATTERN="."
        else
          # Build pathspecs: prefix glob patterns with :(glob) for git
          read -r -a RAW_PATTERNS <<< "$FILE_PATTERN"
          PATHSPECS=()
          for spec in "${RAW_PATTERNS[@]}"; do
            if [[ "$spec" == :\(*\)* ]]; then
              PATHSPECS+=("$spec")
            elif [[ "$spec" == *"*"* || "$spec" == *"?"* || "$spec" == *"["* ]]; then
              PATHSPECS+=(":(glob)$spec")
            else
              PATHSPECS+=("$spec")
            fi
          done
          echo "::debug::Resolved pathspecs: ${PATHSPECS[*]}"

          # Collect changed entries matching pathspecs
          mapfile -t STATUS_LINES < <(git status --porcelain -- "${PATHSPECS[@]}")

          # Extract repo-root-relative file paths from porcelain output
          # git status --porcelain shows untracked dirs as "?? dir/" — we must expand those
          for line in "${STATUS_LINES[@]}"; do
            entry="${line:3}"
            # Handle renames: "old -> new"
            [[ "$entry" == *" -> "* ]] && entry="${entry##* -> }"
            [ -z "$entry" ] && continue

            if [[ "$entry" == */ ]]; then
              # Untracked directory — expand to individual files
              while IFS= read -r -d '' f; do
                [ -n "$f" ] && FILES+=("$f")
              done < <(find "$entry" -type f -print0)
            else
              FILES+=("$entry")
            fi
          done

          if [ "${#FILES[@]}" -gt 0 ]; then
            RESOLVED_PATTERN="$(printf '%s ' "${FILES[@]}")"
            RESOLVED_PATTERN="${RESOLVED_PATTERN% }"
          else
            RESOLVED_PATTERN=""
          fi
        fi

        CHANGE_COUNT="${#STATUS_LINES[@]}"
        if [ "$CHANGE_COUNT" -gt 0 ] && [ -n "$RESOLVED_PATTERN" ]; then
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
          {
            echo "resolved_pattern<<__GHCOMMIT_EOF__"
            echo "$RESOLVED_PATTERN"
            echo "__GHCOMMIT_EOF__"
          } >> "$GITHUB_OUTPUT"
          echo "✅ Detected $CHANGE_COUNT changed file(s) matching pattern '${FILE_PATTERN}'"
          echo "::debug::Resolved file list: ${RESOLVED_PATTERN}"
        else
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          echo "resolved_pattern=${FILE_PATTERN}" >> "$GITHUB_OUTPUT"
          if [ "$ALLOW_EMPTY" = "true" ]; then
            echo "ℹ️ No changes detected, but empty commit is allowed — will proceed"
          else
            echo "ℹ️ No changes detected and empty commits are disabled — skipping commit"
          fi
        fi

    - name: Commit Changes
      id: commit
      uses: planetscale/ghcommit-action@25309d8005ac7c3bcd61d3fe19b69e0fe47dbdde # v0.2.20
      if: steps.detect.outputs.has_changes == 'true' || inputs.empty == 'true'
      with:
        commit_message: ${{ inputs.commit_message }}
        repo: ${{ inputs.repository }}
        branch: ${{ inputs.branch }}
        empty: ${{ inputs.empty }}
        file_pattern: ${{ steps.detect.outputs.resolved_pattern }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Set Compatibility Outputs
      id: compatibility
      shell: bash
      env:
        COMMIT_HASH: ${{ steps.commit.outputs.commit-hash }}
      run: |
        if [ -n "${COMMIT_HASH:-}" ]; then
          echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          echo "✅ Commit created: $COMMIT_HASH"
        else
          echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          echo "ℹ️ No commit was created"
        fi
