name: 'Commit Changes'
description: 'Commits changes using the GitHub API to ensure verified bot commits.'

inputs:
  commit_message:
    description: 'The commit message'
    required: true
  token:
    description: 'The GitHub token to use (must be an App installation token for verified commits)'
    required: true
  repository:
    description: 'Repository name to commit to (e.g. owner/repo)'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'Branch to commit to'
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  empty:
    description: Allow making an empty commit if there are no changes.
    required: false
    default: 'false'
  file_pattern:
    description: 'File pattern to commit'
    required: false
    default: '.'

outputs:
  commit_hash:
    description: 'The SHA of the created commit'
    value: ${{ steps.commit.outputs.commit-hash }}
  commit_url:
    description: 'The URL of the created commit.'
    value: ${{ steps.commit.outputs.commit-url }}
  changes_detected:
    description: 'True if changes were committed'
    value: ${{ steps.compatibility.outputs.changes_detected }}

runs:
  using: 'composite'
  steps:
    - name: Init Git Settings
      id: init
      shell: bash
      run: |
        set -euo pipefail

        # Ignore permission changes, ghcommit is not handeling this correctly
        git config core.fileMode false

    - name: Build Pathspecs
      id: pathspecs
      shell: bash
      env:
        FILE_PATTERN: ${{ inputs.file_pattern }}
      run: |
        set -euo pipefail

        # When file_pattern is empty or ".", no filtering is needed
        if [ -z "${FILE_PATTERN:-}" ] || [ "$FILE_PATTERN" = "." ]; then
          echo "use_filter=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "use_filter=true" >> "$GITHUB_OUTPUT"

        # Split space-separated patterns and add :(glob) prefix where needed
        read -r -a RAW_PATTERNS <<< "$FILE_PATTERN"
        PATHSPECS=()
        for spec in "${RAW_PATTERNS[@]}"; do
          if [[ "$spec" == :\(*\)* ]]; then
            # Already a magic pathspec — pass through
            PATHSPECS+=("$spec")
          elif [[ "$spec" == *"*"* || "$spec" == *"?"* || "$spec" == *"["* ]]; then
            # Contains glob characters — wrap with :(glob) for git
            PATHSPECS+=(":(glob)$spec")
          else
            PATHSPECS+=("$spec")
          fi
        done

        {
          echo "specs<<__PATHSPEC_EOF__"
          printf '%s\n' "${PATHSPECS[@]}"
          echo "__PATHSPEC_EOF__"
        } >> "$GITHUB_OUTPUT"

        echo "::debug::Resolved pathspecs: ${PATHSPECS[*]}"

    - name: Detect Changed Files
      id: detect
      shell: bash
      env:
        USE_FILTER: ${{ steps.pathspecs.outputs.use_filter }}
        PATHSPECS_NL: ${{ steps.pathspecs.outputs.specs }}
        ALLOW_EMPTY: ${{ inputs.empty }}
      run: |
        set -euo pipefail

        # Collect changed entries from git status
        if [ "$USE_FILTER" = "true" ]; then
          mapfile -t SPECS <<< "$PATHSPECS_NL"
          mapfile -t STATUS_LINES < <(git status --porcelain -- "${SPECS[@]}")
        else
          mapfile -t STATUS_LINES < <(git status --porcelain)
        fi

        CHANGE_COUNT="${#STATUS_LINES[@]}"

        if [ "$CHANGE_COUNT" -gt 0 ]; then
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
          echo "✅ Detected $CHANGE_COUNT changed entry/entries"
        else
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          if [ "$ALLOW_EMPTY" = "true" ]; then
            echo "ℹ️ No changes detected, but empty commit is allowed — will proceed"
          else
            echo "ℹ️ No changes detected and empty commits are disabled — skipping commit"
          fi
        fi

    - name: Resolve File Pattern
      id: resolve
      shell: bash
      env:
        USE_FILTER: ${{ steps.pathspecs.outputs.use_filter }}
        PATHSPECS_NL: ${{ steps.pathspecs.outputs.specs }}
        HAS_CHANGES: ${{ steps.detect.outputs.has_changes }}
        FILE_PATTERN: ${{ inputs.file_pattern }}
      run: |
        set -euo pipefail

        # When there are no changes or no filter is used, pass the raw pattern through
        if [ "$HAS_CHANGES" != "true" ] || [ "$USE_FILTER" != "true" ]; then
          echo "resolved_pattern=${FILE_PATTERN:-"."}" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Re-query changed files and resolve to explicit paths for ghcommit-action
        # (ghcommit doesn't understand :(glob) pathspecs or directory entries)
        mapfile -t SPECS <<< "$PATHSPECS_NL"
        mapfile -t STATUS_LINES < <(git status --porcelain -- "${SPECS[@]}")

        FILES=()
        for line in "${STATUS_LINES[@]}"; do
          entry="${line:3}"
          # Handle renames: "old -> new"
          [[ "$entry" == *" -> "* ]] && entry="${entry##* -> }"
          [ -z "$entry" ] && continue

          if [[ "$entry" == */ ]]; then
            # Untracked directory — expand to individual files
            while IFS= read -r -d '' f; do
              [ -n "$f" ] && FILES+=("$f")
            done < <(find "$entry" -type f -print0)
          else
            FILES+=("$entry")
          fi
        done

        if [ "${#FILES[@]}" -gt 0 ]; then
          RESOLVED="$(printf '%s ' "${FILES[@]}")"
          RESOLVED="${RESOLVED% }"
          {
            echo "resolved_pattern<<__GHCOMMIT_EOF__"
            echo "$RESOLVED"
            echo "__GHCOMMIT_EOF__"
          } >> "$GITHUB_OUTPUT"
          echo "✅ Resolved ${#FILES[@]} file(s) for commit"
          echo "::debug::Resolved file list: ${RESOLVED}"
        else
          echo "resolved_pattern=${FILE_PATTERN}" >> "$GITHUB_OUTPUT"
          echo "ℹ️ No files resolved from changed entries"
        fi

    - name: Commit Changes
      id: commit
      uses: planetscale/ghcommit-action@25309d8005ac7c3bcd61d3fe19b69e0fe47dbdde # v0.2.20
      if: steps.detect.outputs.has_changes == 'true' || inputs.empty == 'true'
      with:
        commit_message: ${{ inputs.commit_message }}
        repo: ${{ inputs.repository }}
        branch: ${{ inputs.branch }}
        empty: ${{ inputs.empty }}
        file_pattern: ${{ steps.resolve.outputs.resolved_pattern }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Set Compatibility Outputs
      id: compatibility
      shell: bash
      env:
        COMMIT_HASH: ${{ steps.commit.outputs.commit-hash }}
      run: |
        if [ -n "${COMMIT_HASH:-}" ]; then
          echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          echo "✅ Commit created: $COMMIT_HASH"
        else
          echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          echo "ℹ️ No commit was created"
        fi
