name: 'Commit Changes'
description: 'Commits changes using the GitHub API to ensure verified bot commits.'

inputs:
  commit_message:
    description: 'The commit message'
    required: true
  token:
    description: 'The GitHub token to use (must be an App installation token for verified commits)'
    required: true
  repository:
    description: 'Repository name to commit to (e.g. owner/repo)'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'Branch to commit to'
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  empty:
    description: Allow making an empty commit if there are no changes.
    required: false
    default: 'false'
  file_pattern:
    description: 'File pattern to commit'
    required: false
    default: '.'

outputs:
  commit_hash:
    description: 'The SHA of the created commit'
    value: ${{ steps.commit.outputs.commit-hash }}
  commit_url:
    description: 'The URL of the created commit.'
    value: ${{ steps.commit.outputs.commit-url }}
  changes_detected:
    description: 'True if changes were committed'
    value: ${{ steps.compatibility.outputs.changes_detected }}

runs:
  using: 'composite'
  steps:
    - name: Commit Changes
      id: commit
      uses: planetscale/ghcommit-action@25309d8005ac7c3bcd61d3fe19b69e0fe47dbdde # v0.2.20
      with:
        commit_message: ${{ inputs.commit_message }}
        repo: ${{ inputs.repository }}
        branch: ${{ inputs.branch }}
        empty: ${{ inputs.empty }}
        file_pattern: ${{ inputs.file_pattern }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Set Compatibility Outputs
      id: compatibility
      shell: bash
      env:
        COMMIT_HASH: ${{ steps.commit.outputs.commit-hash }}
      run: |
        if [ -n "$COMMIT_HASH" ]; then
          echo "changes_detected=true" >> $GITHUB_OUTPUT
        else
          echo "changes_detected=false" >> $GITHUB_OUTPUT
        fi
