name: 'Java-gradle Auto-spotless'
description: 'Automatically apply spotless formatting and commit changes.'

on:
  workflow_call:
    inputs:
      gradle_spotless_command:
        description: 'Spotless command to run'
        type: string
        required: false
        default: 'spotlessApply'
      java_version:
        description: 'Java version to use for the build.'
        type: string
        required: true
      java_distribution:
        description: 'Java distribution to use'
        type: string
        required: false
        default: 'temurin'
      java_package:
        description: 'The package type (jdk, jre, jdk+fx, jre+fx)'
        type: string
        required: false
        default: 'jdk'
      gradle_wrapper_validation:
        description: 'Validate Gradle wrapper'
        type: boolean
        required: false
        default: true
      gradle_wrapper_allow_snapshots:
        description: 'Allow Gradle wrapper snapshots'
        type: boolean
        required: false
        default: false
      commit_message:
        description: 'Commit message to use for the auto-commit.'
        type: string
        required: false
        default: 'style: apply spotless formatting'
      comment_message:
        description: 'Comment message to use for the auto-commit.'
        type: string
        required: false
        default: 'Applied spotless formatting.'

    secrets:
      bot_app_id:
        description: 'Bot App ID to run the workflow. The bot needs permissions to write content and write pull requests.'
        required: true
      bot_private_key:
        description: 'Bot Private Key to run the workflow'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-auto-spotless-formatting
  cancel-in-progress: true

permissions: {}

jobs:
  auto-spotless:
    name: Auto Spotless Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Auto Formatting
        uses: TimSchoenle/actions/actions/java-gradle/auto-spotless@706254dd9e0024e208e1ebb320661bdacc79f95c # actions-java-gradle-auto-spotless-v1.1.1
        with:
          bot_app_id: ${{ secrets.bot_app_id }}
          bot_private_key: ${{ secrets.bot_private_key }}
          gradle_spotless_command: ${{ inputs.gradle_spotless_command }}
          java_version: ${{ inputs.java_version }}
          java_distribution: ${{ inputs.java_distribution }}
          java_package: ${{ inputs.java_package }}
          gradle_wrapper_validation: ${{ inputs.gradle_wrapper_validation }}
          gradle_wrapper_allow_snapshots: ${{ inputs.gradle_wrapper_allow_snapshots }}
          commit_message: ${{ inputs.commit_message }}
          comment_message: ${{ inputs.comment_message }}
