name: 'Maintenance Auto-approve-pr'
description: 'Auto approve Pull Requests with the given user ids and branches.'

inputs:
  token:
    description: 'GitHub Token with pull-request: write access.'
    required: true
  user_ids:
    description: 'Comma-separated list of Database IDs of accepted authors (e.g. "29139614, 123456").'
    required: true
  ignore_empty_prs:
    description: 'Ignore PRs with 0 changes. Renovate seems to sometimes create multiple lock-files PR without changing anything.'
    required: false
    default: 'true'
  pr_url:
    description: 'URL of the pull request (e.g. "https://github.com/owner/repo/pull/123").'
    required: false
    default: ${{ github.event.pull_request.html_url }}
  branch_pattern:
    description: 'Regex pattern to match branch names (e.g. "^release-please--branches--.*$"). Uses extended regex syntax.'
    required: true
  reject_forks:
    description: 'Reject PRs from forked repositories. When true, only PRs from branches in the same repository will be approved.'
    required: false
    default: 'true'
  auto_approve_message:
    description: 'Message to include in the auto-approve comment.'
    required: false
    default: 'Auto-approved by workflow.'

runs:
  using: 'node20'
  main: 'dist/index.js'
