name: 'Create Pull Request'
description: 'Creates or updates a pull request using GitHub App authentication with optional branch reset.'

inputs:
  app-id:
    description: 'GitHub App ID'
    required: true
  private-key:
    description: 'GitHub App Private Key'
    required: true
  repository:
    description: 'Repository name to create PR in (e.g. owner/repo)'
    required: false
    default: ${{ github.repository }}
  branch_name:
    description: 'The branch name to use for the pull request'
    required: true
  base_branch:
    description: 'The branch to merge into (defaults to repository default branch)'
    required: false
    default: ''
  title:
    description: 'Pull request title'
    required: true
  body:
    description: 'Pull request body/description'
    required: false
    default: ''
  reset_branch:
    description: 'Whether to reset the branch to the base branch before committing (force push)'
    required: false
    default: 'true'
  commit_changes:
    description: 'Whether to commit local changes to the branch before creating PR'
    required: false
    default: 'true'
  commit_message:
    description: 'Commit message for changes (required if commit_changes is true)'
    required: false
    default: ''
  file_pattern:
    description: 'File pattern to commit (used when commit_changes is true)'
    required: false
    default: '.'
  empty_commit:
    description: 'Allow making an empty commit if there are no changes'
    required: false
    default: 'false'

outputs:
  pr_url:
    description: 'The URL of the created or updated pull request'
    value: ${{ steps.create-pr.outputs.pr-url }}
  pr_number:
    description: 'The pull request number'
    value: ${{ steps.create-pr.outputs.pr-number }}

runs:
  using: 'composite'
  steps:
    - name: Parse Repository
      id: parse
      shell: bash
      env:
        REPO: ${{ inputs.repository }}
      run: |
        OWNER="${REPO%%/*}"
        REPO_NAME="${REPO#*/}"
        echo "owner=$OWNER" >> "$GITHUB_OUTPUT"
        echo "repo=$REPO_NAME" >> "$GITHUB_OUTPUT"

    - name: Generate Bot Token
      id: generate_token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ steps.parse.outputs.owner }}
        repositories: ${{ steps.parse.outputs.repo }}

    - name: Create Branch
      id: branch
      uses: TimSchoenle/actions/actions/common/create-branch@331de547737ea4a2b899287998f1ff90a912b7ba # actions-common-create-branch-v1.2.0
      with:
        token: ${{ steps.generate_token.outputs.token }}
        repository: ${{ inputs.repository }}
        branch_name: ${{ inputs.branch_name }}
        base_branch: ${{ inputs.base_branch }}
        reset_branch: ${{ inputs.reset_branch }}

    - name: Commit Changes
      if: inputs.commit_changes == 'true'
      id: commit
      uses: TimSchoenle/actions/actions/common/commit-changes@8f15b94f827ea2005c0e32cadc86bb50969633dd # actions-common-commit-changes-v1.1.4
      env:
        GITHUB_SHA: ${{ steps.branch.outputs.sha }}
      with:
        token: ${{ steps.generate_token.outputs.token }}
        repository: ${{ inputs.repository }}
        branch: ${{ inputs.branch_name }}
        commit_message: ${{ inputs.commit_message }}
        file_pattern: ${{ inputs.file_pattern }}
        empty: ${{ inputs.empty_commit }}

    - name: Check for Branch Differences
      id: diff-check
      shell: bash
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        REPO: ${{ inputs.repository }}
        HEAD_BRANCH: ${{ inputs.branch_name }}
        BASE_BRANCH: ${{ steps.branch.outputs.base_branch }}
      run: |
        # Compare the two branches
        COMPARISON=$(gh api "/repos/$REPO/compare/$BASE_BRANCH...$HEAD_BRANCH" --jq '.status')

        if [ "$COMPARISON" = "identical" ]; then
          echo "has_differences=false" >> $GITHUB_OUTPUT
          echo "Branches are identical, no differences to create PR for"
        else
          echo "has_differences=true" >> $GITHUB_OUTPUT
          echo "Branches have differences: $COMPARISON"
        fi

    - name: Create Pull Request
      # The diff-check step sometimes fails, since github takes a while to update the comparison status. So we will just assume that it changed if we commit ourselfs
      if: steps.diff-check.outputs.has_differences == 'true' || steps.commit.outputs.changes_detected == 'true'
      id: create-pr
      shell: bash
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        REPO: ${{ inputs.repository }}
        HEAD_BRANCH: ${{ inputs.branch_name }}
        BASE_BRANCH: ${{ steps.branch.outputs.base_branch }}
        TITLE: ${{ inputs.title }}
        BODY: ${{ inputs.body }}
      run: |
        # Try to create PR, or get existing one
        if PR_URL=$(gh pr create \
          --repo "$REPO" \
          --head "$HEAD_BRANCH" \
          --base "$BASE_BRANCH" \
          --title "$TITLE" \
          --body "$BODY" 2>&1); then
          echo "pr-url=$PR_URL" >> "$GITHUB_OUTPUT"
          
          # Extract PR number from URL
          PR_NUMBER=$(echo "$PR_URL" | grep -oP '\d+$')
          echo "pr-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
          
          echo "Pull request created: $PR_URL"
        else
          # Check if PR already exists
          if echo "$PR_URL" | grep -q "already exists"; then
            echo "Pull request already exists, fetching URL..."
            EXISTING_PR_URL=$(gh pr list \
              --repo "$REPO" \
              --head "$HEAD_BRANCH" \
              --base "$BASE_BRANCH" \
              --json url \
              --jq '.[0].url')
            
            EXISTING_PR_NUMBER=$(gh pr list \
              --repo "$REPO" \
              --head "$HEAD_BRANCH" \
              --base "$BASE_BRANCH" \
              --json number \
              --jq '.[0].number')
            
            echo "pr-url=$EXISTING_PR_URL" >> "$GITHUB_OUTPUT"
            echo "pr-number=$EXISTING_PR_NUMBER" >> "$GITHUB_OUTPUT"
            echo "Existing pull request: $EXISTING_PR_URL"
          else
            echo "Error creating pull request: $PR_URL"
            exit 1
          fi
        fi
