name: Auto Format

on:
  pull_request:

permissions: {}

jobs:
  auto-format:
    name: Auto Format
    uses: TimSchoenle/actions/.github/workflows/maintenance-auto-bun-prettier.yaml@ec974937a55da96a98cdd982ddd0e6bc9e60c72a # tag=workflows-maintenance-auto-bun-prettier-v1.1.17
    secrets:
      APP_ID: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
      PRIVATE_KEY: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
