name: Auto Format

on:
  pull_request:

permissions: {}

jobs:
  auto-format:
    name: Auto Format
    uses: TimSchoenle/actions/.github/workflows/maintenance-auto-bun-prettier.yaml@a90bfbb4f2a92edc2b004704df0139fa4eee35f5 # tag=workflows-maintenance-auto-bun-prettier-v1.1.16
    secrets:
      APP_ID: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
      PRIVATE_KEY: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
