name: Scripts CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint-and-test:
    name: Lint & Test
    permissions:
      contents: read # to fetch code
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: TimSchoenle/actions/actions/bun/setup-cached@e337ba069b1cc770a0dd5d39638664cf1ce8e64f # actions-bun-setup-cached-v1.1.5

      - name: Format Check
        run: bun run format --check

      - name: Test
        run: bun run test
