name: Security

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read # to fetch code
      actions: read # to read action configurations
      security-events: write # to upload SARIF results
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Find Custom Workflows
        id: find-workflows
        run: |
          echo "workflow_files=$(find workflows -name '*.yaml' -o -name '*.yml' | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

      - name: Run Zizmor
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
        with:
          persona: pedantic
          inputs: . ${{ steps.find-workflows.outputs.workflow_files }}

  action-lint:
    name: Action Lint
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        env:
          EXECUTABLE: ${{ steps.get_actionlint.outputs.executable }}
        run: |
          shopt -s globstar nullglob
          $EXECUTABLE -color -verbose \
            -config-file .github/actionlint.yaml \
            .github/workflows/*.{yml,yaml} \
            workflows/**/*.{yml,yaml}
        shell: bash
