name: Security

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read # to fetch code
      actions: read # to read action configurations
      security-events: write # to upload SARIF results
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Find Custom Workflows
        id: find-workflows
        run: |
          echo "workflow_files=$(find workflows -name '*.yaml' -o -name '*.yml' | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

      - name: Run Zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          persona: pedantic
          inputs: . ${{ steps.find-workflows.outputs.workflow_files }}

  action-lint:
    name: Action Lint
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        env:
          EXECUTABLE: ${{ steps.get_actionlint.outputs.executable }}
        run: |
          shopt -s globstar nullglob
          $EXECUTABLE -color -verbose \
            -config-file .github/actionlint.yaml \
            .github/workflows/*.{yml,yaml} \
            workflows/**/*.{yml,yaml}
        shell: bash
