name: 'Common Create Branch'
description: 'Creates or resets a git branch using GitHub API.'

inputs:
  token:
    description: 'GitHub Token'
    required: true
  repository:
    description: 'Repository name to create branch in (e.g. owner/repo)'
    required: true
  branch_name:
    description: 'The branch name to create or reset'
    required: true
  base_branch:
    description: 'The branch to branch from (defaults to repository default branch)'
    required: false
    default: ''
  reset_branch:
    description: 'Whether to reset the branch if it already exists'
    required: false
    default: 'none'

outputs:
  branch:
    description: 'The branch name'
    value: ${{ steps.create.outputs.branch }}
  sha:
    description: 'The SHA of the branch head'
    value: ${{ steps.create.outputs.sha }}
  created:
    description: 'True if branch was created or reset, false otherwise'
    value: ${{ steps.create.outputs.created }}

runs:
  using: 'composite'
  steps:
    - name: Create or Reset Branch
      id: create
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPO: ${{ inputs.repository }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        BASE_BRANCH_INPUT: ${{ inputs.base_branch }}
        RESET_BRANCH: ${{ inputs.reset_branch }}
      run: |
        # 1. Determine Base SHA
        if [ -z "$BASE_BRANCH_INPUT" ]; then
          # Fetch default branch
          DEFAULT_BRANCH=$(gh api "/repos/$REPO" --jq .default_branch)
          BASE_BRANCH="$DEFAULT_BRANCH"
          echo "Using default branch: $DEFAULT_BRANCH"
        else
          BASE_BRANCH="$BASE_BRANCH_INPUT"
          echo "Using provided base branch: $BASE_BRANCH"
        fi

        # Get the SHA of the base branch
        BASE_SHA=$(gh api "/repos/$REPO/git/refs/heads/$BASE_BRANCH" --jq .object.sha)
        if [ -z "$BASE_SHA" ]; then
          echo "::error::Could not find SHA for base branch $BASE_BRANCH"
          exit 1
        fi
        echo "Base SHA: $BASE_SHA"

        # 2. Check if target branch exists
        BRANCH_EXISTS="false"
        if gh api "/repos/$REPO/git/refs/heads/$BRANCH_NAME" > /dev/null 2>&1; then
          BRANCH_EXISTS="true"
          echo "Target branch '$BRANCH_NAME' already exists."
        else
          echo "Target branch '$BRANCH_NAME' does not exist."
        fi

        # 3. Create or Reset Logic
        CREATED="false"

        if [ "$BRANCH_EXISTS" = "false" ]; then
          # Create new branch
          echo "Creating branch '$BRANCH_NAME' from '$BASE_SHA'..."
          gh api -X POST "/repos/$REPO/git/refs" \
            -f ref="refs/heads/$BRANCH_NAME" \
            -f sha="$BASE_SHA"
          CREATED="true"
          FINAL_SHA="$BASE_SHA"
        else
          # Branch exists
          if [ "$RESET_BRANCH" = "true" ]; then
            # Reset branch
            echo "Resetting branch '$BRANCH_NAME' to '$BASE_SHA'..."
            gh api -X PATCH "/repos/$REPO/git/refs/heads/$BRANCH_NAME" \
              -f sha="$BASE_SHA" \
              -F force=true
            CREATED="true"
            FINAL_SHA="$BASE_SHA"
          else
            # Do nothing (or verify it matches?)
            # We'll just output the current SHA of the existing branch
            CURRENT_SHA=$(gh api "/repos/$REPO/git/refs/heads/$BRANCH_NAME" --jq .object.sha)
            echo "Branch exists and reset_branch is not true. Keeping existing branch at $CURRENT_SHA."
            FINAL_SHA="$CURRENT_SHA"
          fi
        fi

        # 4. Set Outputs
        echo "branch=$BRANCH_NAME" >> "$GITHUB_OUTPUT"
        echo "sha=$FINAL_SHA" >> "$GITHUB_OUTPUT"
        echo "created=$CREATED" >> "$GITHUB_OUTPUT"
